### ISSUE TITLE
Need more discussion

### ISSUE THREAD

**Issue by thedahiyaboy** [atinesh-s/Coursera-Machine-Learning-Stanford#9]
1. In quiz 8, question 4,  why answer B is not correct.

2. In assignment 2, For calculating costFunctionReg, I have done

```
h = sigmoid(X*theta);
theta_temp = [0; theta(2:end)];
J = (1/m)* sum((-y'*log(h)) - ((1-y)'*log(1-h))) + (lambda / (2*m)) * sum(theta .^ 2);
grad = (1/m)* sum((h-y)*X) + (lambda/m).*theta_temp;
```
My J is calculated as expected but getting error in grad. My code is same as like derivation (as I am seeing) but still unable to fig out where I am wrong. Whereas you are not using **sum** func but still your code is working fine. Can you pls explain how it is working?

**Comment by atinesh-s** [comment]
`*` and `.*` are two different operations in `MATLAB` read [this](https://in.mathworks.com/help/matlab/matlab_prog/array-vs-matrix-operations.html) for more details.

Although `sum` would not be necessary if you still want to use it then use `.*` operation instead of `*` inside `sum`. Try making following changes and check if it works

- `-y'*log(h)` to `-y .* log(h)`
- `(1-y)'*log(1-h)` to `(1-y) .* log(1-h)`

**Comment by thedahiyaboy** [comment]
In below both code, I'm getting **J** perfect.

```
J = (1/m)* sum((-y.*log(h)) - ((1-y).*log(1-h))) + (lambda / (2*m)) * sum(theta .^ 2);
```

but when I apply same for gradient I got error in console.

![d2](https://user-images.githubusercontent.com/22885093/57197252-b7b47780-6f82-11e9-9694-2229451855ed.PNG)

Probably it is due to mismatch size of the **X** and **h-y** .

![d1](https://user-images.githubusercontent.com/22885093/57197263-d0249200-6f82-11e9-9f50-b20ba686189d.PNG)

How I solve this issue?

**Comment by atinesh-s** [comment]
Try this 

`grad = (1/m)* sum((h-y)'*X) + sum((lambda/m).*theta_temp);`

**Comment by thedahiyaboy** [comment]
It gives me below error
![d3](https://user-images.githubusercontent.com/22885093/57197430-cd2aa100-6f84-11e9-9951-1122854fd294.PNG)

I am amazed,  `grad = (1/m) .* sum((hx - y) .* X)` working fine in the **ex2.m**.

**Comment by thedahiyaboy** [comment]
Ok, I got the error. It is due to mismatch size of the grad and reg. So transpose of  theta_temp worked.

![d5](https://user-images.githubusercontent.com/22885093/57197658-aae65280-6f87-11e9-8bb8-0abf9bb00936.PNG)

Thanks for your help.

--------
Currently, I am not closing this thread as if in future I need help then I can ask ques her instead of creating new one. Hope you don't mind.

**Comment by tonimamsaum** [comment]
So I am currently facing a problem with assignment 5, my backpropagation and sigmoid gradient works but after that, the checkNNgradient file keeps addressing a problem of mismatched matrices. I have traced the problem and (since I am really bad at coding) this is how far I got. the file can calculate numgrad but fails to be able to compute "disp([numgrad grad]);", and this is the error message 
"Error using horzcat
Dimensions of arrays being concatenated are not consistent." shown.
the  numgrad is showing to be 38*1 and grad to be 30*1. 
how did the dimensions get messed up and how do I fix it?
